apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: whoami
  namespace: web
spec:
  hosts:
    - whoami.plsdontspam.me
  gateways:
    - whoami-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: whoami.web.svc.cluster.local
            port:
              number: 80